### ISSUE TITLE
GitHub dependency

### ISSUE THREAD

**Issue by SimenB** [mrjoelkemp/node-detective-sass#5]
Hey!

Would it be possible to drop the GH dep? Our build server is behind a proxy, and has no access to the web. The npm registry is proxied, but GH deps are unavailable 😄

**Comment by SimenB** [comment]
Worst case, just publish it scoped

**Comment by mrjoelkemp** [comment]
Ah! Sorry about that. Publishing scoped sounds good. Will make that change within the next hour and report back when done.

**Comment by mrjoelkemp** [comment]
@SimenB I released a patch version. That will bubble up to the consuming lib if you fresh install or npm update. 

Let me know if you run into any more problems.

Btw, if you're a sublime text 2/3 user, feel free to check out my https://packagecontrol.io/packages/Dependents package. It's really awesome for navigating JS codebases. Cheers and thanks for the bug report!
